// Generated by CoffeeScript 1.3.3
(function() {
  var click_listener, default_minutes, pomodorro_running, schedule_action, start_pomodorro, time;

  pomodorro_running = false;

  default_minutes = 2;

  time = default_minutes * 60;

  start_pomodorro = function() {
    pomodorro_running = true;
    return time = default_minutes * 60;
  };

  schedule_action = function() {};

  click_listener = function() {
    var notif;
    if (!pomodorro_running) {
      start_pomodorro();
    }
    chrome.browserAction.setBadgeText({
      text: "" + time
    });
    time -= 1;
    if (time < 0) {
      pomodorro_running = false;
      notif = webkitNotifications.createNotification(null, "Pomodorro finished", "Congrats!");
      return notif.show();
    } else {
      return window.setTimeout(click_listener, 1000);
    }
  };

  chrome.browserAction.onClicked.addListener(click_listener);

}).call(this);
